[workspace]
members = ["crates/mountaineer"]
default-members = ["crates/mountaineer"]
resolver = "2"

[workspace.dependencies]
mountaineer = { path = "crates/mountaineer" }
system-configuration = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
dirs = "5"
clap = { version = "4", features = ["derive"] }
anyhow = "1.0"
nix = { version = "0.30", features = ["net"] }
core-foundation = "0.9"
